
VERSION=1.1.7

### to fix the binary release
### get checked out source code, and regenerate the toolbox subproject
### then redistribute

redis:
	scp toolbox-${VERSION}-release.zip openprovenance@websites1.ecs.soton.ac.uk:/home/openprovenance/openprovenance.org/htdocs/java/maven-releases/org/openprovenance/toolbox/${VERSION}/

