#!/bin/sh

cd target
/home/lavm/swift2/cog/modules/swift/dist/swift-svn/bin/VDLx2Karajan $1 > tmp.kml
cat tmp.kml | grep -v 'Validation of XML intermediate file was successful' > $2
/home/lavm/swift2/cog/modules/swift/dist/swift-svn/bin/swift $2


